# NLU Component for RAG Chatbot
Reference to [RASA NLU Component](https://www.rasa.com/docs/reference/config/components/nlu-components/)

## Example Generator

In [ ]:
import pandas as pd

col_list = ['mal_id', 'title', 'title_english', 'type', 'chapters', 'volumes', 'status', 'published_from',
                    'published_to', 'score', 'authors', 'genres', 'themes', 'synopsis']
df = pd.read_csv('dataset/manga_dataset.csv')
df = df.loc[:10000, col_list]
df.dropna(subset=['title'], inplace=True)
fillcol = {
            'title_english': '-',
            'type': '-',
            'chapters': 0,
            'volumes': 0,
            'status': '-',
            'published_from': '-',
            'score': 0,
            'authors': '-',
            'genres': '-',
            'themes': '-',
            'synopsis': '-'}
df.fillna(fillcol, inplace=True)

In [ ]:
unique_list = list(df['title'].unique())
len(unique_list)

In [ ]:
import random
random.seed(1)

random.sample(unique_list,k=5)

In [ ]:
# "recommend me similar manga to [MASK](COLUMNS)",
# "recommend me manga like [MASK](COLUMNS)",
# "Do you have recommendation with [genre](field) [MASK](COLUMNS) manga?",
# "Do you have recommendation manga by [MASK](COLUMNS) [published](field) in [2011](period)?",
# "give me recommendation manga like [MASK](COLUMNS)",
# "give me suggestion [MASK](COLUMNS) manga [published](field) in [2019](period) with [author](field) [Homeru Ken and Oojima Klaus](authors)",
# "suggest me [one-shot](COLUMNS) manga similar to [Lagoon Engine Einsatz](COLUMNS)",
# "suggest me another [fantasy](COLUMNS) [horror](COLUMNS) manga looks like [Under Arakawa Bridge](COLUMNS)",
# "do you have suggestion any manga [published](field) in [2011](COLUMNS)?",
#
#                 "give me explanation why [MASK](COLUMNS) is so popular",
#                 "explain to me [MASK](COLUMNS) ending",
#                 "please tell me more about [MASK](COLUMNS)",
#                 "give me explanation about [MASK](COLUMNS) briefly",
#                 "what makes [MASK](COLUMNS) series stop published?",


# "Who is the [author](field) of [MASK](COLUMNS)?",
#                 "Who are the [authors](field) of [MASK](COLUMNS)?",
#                 "Please tell me how many [chapter](field) [MASK](COLUMNS) manga is?",
#                 "How many [chapters](field) [MASK](COLUMNS) have right now?",
#                 "Tell me [genres](field) of [MASK](COLUMNS)",
#                 "Show me all [genres](field) of manga title [MASK](COLUMNS)",
#                 "How many [volumes](field) [MASK](COLUMNS) manga have?",
#                 "Please give me total [volumes](field) of [MASK](COLUMNS)",
#                 "What date [MASK](COLUMNS) manga [published](field)?",
#                 "When [MASK](COLUMNS) manga [published](field)?",
#                 "Give me [published date](field) of [MASK](COLUMNS)",

                "give me list manga with [author](field) [Naoki Urawa](COLUMNS)",
                "give me manga [published](field) in [2020](value)",
                "find manga with [status](field) [finished](value)",
                "find me manga with [rating](field) above [7](value) with [status](field) [finished](value)"
                    "list manga by [author](field) name [Itou Hachi](COLUMNS)",

In [ ]:
sent_sample = [
                "Show me manga with [genres](field) [MASK](COLUMNS)",
                "Show me [MASK](COLUMNS) manga by [author](field) [Hikari Kenjiro](COLUMNS), [Tamura Ken](COLUMNS)",
                "list manga by [genre](field) [MASK](COLUMNS) by [Kamisato Ayaka](COLUMNS) and [Kirara] (COLUMNS)",

            ]

In [ ]:
sent_sample = [
    'Find me manga with genre [MASK](genres)',
    'Find me top one-shot manga with genre [MASK](genres)',
    'Tell me good [MASK](genres) manga',
    'Tell me best [MASK](genres) manga',
    'Show me more manga by genres [MASK](genres)',
    'Do you know [MASK](genres) manga released in [2019](value)?',
    'Do you know manga [MASK](genres) by author [Miyazakai](value)?',
    'list manga by genres [MASK](genres) with total chapter above [20](value)',
    'list manga [MASK](genres) with rating above [9](value)',

]

In [ ]:
import random


def generate_example(df, col_name, n_sample, sent_sample, random_state=42):
    random.seed(random_state)
    result = []
    unique_sample = []
    unique_list = list(df[col_name].unique())
    for sample in random.sample(unique_list, k=100):
        # pair_author = []
        for name in sample.split('|'):
            tmp = name.split(',')
            if len(tmp) > 1:
                tmp_string = tmp[-1]+ ' ' + ' '.join(tmp[:-1])
            else:
                tmp_string = tmp[-1]
            tmp_string = tmp_string.strip()
            # pair_author.append(tmp_string)
            unique_sample.append(tmp_string)

        # unique_sample.append(', '.join(pair_author))

    unique_sample = list(set(unique_sample))
    return  unique_sample
    # # for text, rand_value in zip(random.choices(sent_sample, k=n_sample), unique_sample):
    # for text in sent_sample:
    #     tmp = random.sample(unique_sample, random.randint(1,3))
    #     tmp_string = [f'[{a}]({b})' for a,b in zip(tmp,[col_name]*len(tmp))]
    #     tmp_string = ', '.join(tmp_string)
    #     text = text.replace('[MASK](COLUMNS)', tmp_string)
    #
    #     # text = text.replace('MASK', rand_value)
    #     # text = text.replace('COLUMNS', col_name)
    #     result.append(text)
    #
    # return result

In [ ]:
generate_example(df,
                 col_name='genres',
                 n_sample=15,
                 sent_sample=sent_sample,
                 random_state=42)

In [ ]:
name = 'Poi Zuxkc, Diana|Hypo, Columbina'
tmp = name.split(',')
if len(tmp) > 1:
    tmp_string = tmp[-1]+ ' ' + ' '.join(tmp[:-1])
else:
    tmp_string = tmp[-1]
tmp_string = tmp_string.strip()
tmp_string

In [ ]:
unique_list[1].split('|')

In [ ]:


# train(verbose=True)

In [ ]:
from nlu_module.nlu_component import load_nlu_model
from nlu_module.entity_tagger import predict_ner

intent_model, ner_model = load_nlu_model('2026-06-12')

In [ ]:
text = 'How many chapters Kimi ni Todoke with author Hajime Isyama?'
text = 'show me manga published in 2026'
text = 'do you have recommendation one-shot manga with genre drama comedy slice of life'
# text = 'can you briefly summarize story of nobunaga'


# intent classification
# print('intent:', intent_model.predict([text])[0])
print('intent:', intent_model.predict_proba([text])[0])

# NER detection
entities = predict_ner(ner_model, text)
print(entities)

In [ ]:
intent_model.classes_

## Test SQL

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataset/manga_dataset.csv')

In [3]:
df = df[df['published_from'].str.contains('2026', na=False)] # '2023|2024|2025|2026'
df.shape

(373, 24)

In [4]:
# df.dropna(subset=['title','score', 'authors', 'genres', 'themes', 'synopsis'])

In [5]:
df.loc[:, ['title','genres','synopsis']]

,title,genres,synopsis
72750,404 Chicks,Comedy,NaN
80732,One Cute Chick,Comedy,Chicktaro is too cute!\n\n\nI saw this story a...
81552,Dareka Ookami-san no Shitsukekata Shirimasen ka!?,Girls Love,"Himura Akane, a sophomore and member of the di..."
81574,Ano Shima no Uminesou,Mystery|Ecchi,Unemployed 19-year-old Kazuma has been summone...
81618,Winter Field,Boys Love|Fantasy|Erotica,"Rensley Mallosen, the illegitimate prince of C..."
...,...,...,...
82883,"Keiyaku shite yo, Sumi-senpai",Boys Love|Supernatural,"""The real me is far from being perfect.""\n\nKy..."
82885,Elf-ppoi Hana-san no Tekitou na Apartment-gurashi,Comedy|Supernatural,"Hana, who lives in the cheap apartment next do..."
82886,Garden in the Closet,Boys Love|Drama|Supernatural,Kouki is a high school student with a large bu...
82887,Anta ga Warui,Drama|Girls Love,"""I am only interested in people who seem into ..."
82888,Hirahirahira,Adventure|Fantasy|Slice of Life,"In a certain era, in a certain place. Yohira c..."

In [6]:
from database_module.sqldb import SQLDB

In [16]:
# sqldb = SQLDB(db_name='manga',
#                source_path='dataset/manga_dataset.csv',
#                rebuild_db=True,
#                max_rows=None
#                )

# sqldb = SQLDB(db_name='manga',
#                rebuild_db=False,
#                )

sqldb = SQLDB('manga')

In [18]:
# sqldb.create_db(df)
sqldb.connect_db()

13-07-2026 14:42:09 - manga.db connected successfully.

In [19]:
sqldb._check_db_exist()

True

In [20]:
col_list = ['mal_id', 'title', 'title_english', 'type', 'chapters', 'volumes', 'status', 'published_from',
                    'published_to', 'score', 'authors', 'genres', 'themes', 'synopsis']
with sqldb.conn as conn:
    cursor = conn.cursor()
    # Query the manga_fts table instead of the standard manga table
    # cursor.execute('SELECT * FROM manga_fts WHERE title MATCH "Yuri" OR title_english MATCH "Yuri" ORDER BY score DESC')
    # cursor.execute('SELECT * FROM manga_fts WHERE genres MATCH "romance" ORDER BY score DESC')
    cursor.execute("SELECT * FROM manga_fts LIMIT 5")
    all_rows = cursor.fetchmany(5)
    for row in all_rows:
        tmp = '\n'.join(f'{col}: {val} ' for col, val in zip(col_list, row))

        print(tmp,'\n')

mal_id: 1
title: Monster
title_english: Monster
type: Manga
chapters: 162.0
volumes: 18.0
status: Finished
published_from: 1994-12-05
published_to: 2001-12-20
score: 9.16
authors: Urasawa, Naoki
genres: Award Winning|Drama|Mystery
themes: Adult Cast|Psychological
synopsis: Kenzou Tenma, a renowned Japanese neurosurgeon working in post-war Germany, faces a difficult choice: to operate on Johan Liebert, an orphan boy on the verge of death, or on the mayor of Düsseldorf. In the end, Tenma decides to gamble his reputation by saving Johan, effectively leaving the mayor for dead.

As a consequence of his actions, hospital director Heinemann strips Tenma of his position, and Heinemann's daughter Eva breaks off their engagement. Disgraced and shunned by his colleagues, Tenma loses all hope of a successful career—that is, until the mysterious killing of Heinemann gives him another chance.

Nine years later, Tenma is the head of the surgical department and close to becoming the director himself. Although all seems well for him at first, he soon becomes entangled in a chain of gruesome murders that have taken place throughout Germany. The culprit is a monster—the same one that Tenma saved on that fateful day nine years ago.

[Written by MAL Rewrite]

mal_id: 2
title: Berserk
title_english: Berserk
type: Manga
chapters: None
volumes: None
status: Publishing
published_from: 1989-08-25
published_to: None
score: 9.46
authors: Miura, Kentarou|Studio Gaga
genres: Action|Adventure|Award Winning|Drama|Fantasy|Horror
themes: Gore|Military|Psychological
synopsis: Guts, a former mercenary now known as the Black Swordsman, is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings.

Setting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him—and his loved one—of their humanity.

[Written by MAL Rewrite]

Included one-shot:
Volume 14: Berserk: The Prototype

mal_id: 3
title: 20th Century Boys
title_english: 20th Century Boys
type: Manga
chapters: 249.0
volumes: 22.0
status: Finished
published_from: 1999-09-27
published_to: 2006-04-24
score: 8.93
authors: Urasawa, Naoki
genres: Award Winning|Drama|Mystery|Sci-Fi
themes: Historical|Psychological
synopsis: As the 20th century approaches its end, people all over the world are anxious that the world is changing. And probably not for the better.

Kenji Endou is a normal convenience store manager who is just trying to get by. But when he learns that one of his old friends going by the name "Donkey" has suddenly committed suicide and that a new cult led by a figure known as "Friend" is becoming more notorious, Kenji starts to feel that something is not right. With a few key clues left behind by his deceased friend, Kenji realizes that this cult is much more than he ever thought it would be—not only is this mysterious organization directly targeting him and his childhood friends, but the whole world also faces a grave danger that only the friends have the key to stop.

Kenji's simple life of barely making ends meet is flipped upside down when he reunites with his childhood friends, and together they must figure out the truth of how their past is connected to the cult, as the turn of the centur

mal_id: 4
title: Yokohama Kaidashi Kikou
title_english: Yokohama Kaidashi Kikou
type: Manga
chapters: 142.0
volumes: 14.0
status: Finished
published_from: 1994-04-25
published_to: 2006-02-25
score: 8.66
authors: Ashinano, Hitoshi
genres: Award Winning|Sci-Fi|Slice of Life
themes: Iyashikei
synopsis: In a post-apocalyptic world where an environmental disaster led to the eruption of Mt. Fuji and the inundation of Yokohama, the age of humans is in its twilight. Alpha Hatsuseno is an android and the namesake of a small cafe outside Yokohama. As her owner is away on a trip indefinitely, she has been left responsible for running the cafe. Although she rarely gets any customers, Alpha remains outgoing and cheerful.

While Alpha awaits her owner's homecoming, she explores the vicinity with her scooter and camera. Throughout her journeys, she meets new people and other androids, making memories along the way.

Yokohama Kaidashi Kikou is a beautiful, laid-back story centered around Alpha's daily activities, emphasizing the passing of time in everyday life.

[Written by MAL Rewrite]

mal_id: 7
title: Hajime no Ippo
title_english: Hajime no Ippo: Fighting Spirit!
type: Manga
chapters: None
volumes: None
status: Publishing
published_from: 1989-09-27
published_to: None
score: 8.76
authors: Morikawa, George
genres: Award Winning|Sports
themes: Combat Sports
synopsis: Makunouchi Ippo is a 16-year-old high school student who helps his mother run the family business. His hefty workload impedes his social life, making him an easy target for bullies. One day, while being beaten up by a group of high school students, Ippo is saved by a boxer named Mamoru Takamura, and is brought to the Kamogawa Boxing Gym.

This afterschool bullying session turns his life around for the better, as Ippo discovers his latent talent for boxing and decides to practice the sport professionally. However, Mamoru doubts Ippo's determination and assigns him a task deemed impossible to complete; but the resolute Ippo trains tirelessly to fulfill his mission. Along the way, he finds out what it means to attain true strength while making new friends and fighting formidable foes.

[Written by MAL Rewrite]

In [ ]:
conn.close()

In [ ]:
from ollama import chat

In [ ]:

def response_sql_cleaner(text):
    text = text.replace("```","")
    text = text.replace('\n',' ')
    text = text.replace(';','')
    text = re.sub(r'(?i)^\s*sql\s*', '', text).strip()

    text = re.sub(r'\s+', ' ', text)


    return text

poi = 'SELECT *\nFROM manga\nWHERE score > 8.8 AND chapters > 20;'
response_sql_cleaner(poi)

In [ ]:
content = 'give me manga with rating above 8.8 with chapter above 20'
content = 'how many chapter and volumes yuru yuri camp have?'
template_message = [
                            {
                                    'role': 'system',
                                    'content': '''
                                            You are AI to convert user message into sql query. we have database called manga with column title (string), score(float), chapters(integer), and volume(integer). return only sql query based on info provided by user.

                                            '''
                              },
                            {

                                'role': 'user',
                                'content': content ,
                            },
                    ]
response = chat(model='gemma3:4b', messages=template_message)['message']['content']
response = response_sql_cleaner(response)
response

## Test Embedding

In [6]:


text = '''In a school where after school activities are mandatory among all students, Hajime and her friend Sayo come across a new club that they have never seen before. The club is called "The Cultural Activity Preservation Club." The two enter the room to find all kinds of analog jobs and activities, such as handcrafting mats and toothpicks. This is a unique cultural manga mixed with comedy so as not to bore you, this is (Double-J)! authors:Nonaka, Eiji|Asakura, Maru

(Source: MangaHelpers)'''

def _clean_text(text):
    text = text.replace('|',', ')
    text = re.sub(r"\(Source:.*?\)", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text

_clean_text(text)

'In a school where after school activities are mandatory among all students, Hajime and her friend Sayo come across a new club that they have never seen before. The club is called "The Cultural Activity Preservation Club." The two enter the room to find all kinds of analog jobs and activities, such as handcrafting mats and toothpicks. This is a unique cultural manga mixed with comedy so as not to bore you, this is (Double-J)! authors:Nonaka, Eiji, Asakura, Maru'

In [1]:
import pandas as pd
df = pd.read_csv('dataset/manga_dataset.csv')
df

,mal_id,title,title_english,title_japanese,type,chapters,volumes,status,publishing,published_from,...,popularity,members,favorites,authors,serializations,genres,themes,demographics,synopsis,image_url
0,1,Monster,Monster,MONSTER,Manga,162.0,18.0,Finished,False,1994-12-05,...,27,288956,23729,"Urasawa, Naoki",Big Comic Original,Award Winning|Drama|Mystery,Adult Cast|Psychological,Seinen,"Kenzou Tenma, a renowned Japanese neurosurgeon...",https://myanimelist.net/images/manga/3/258224.jpg
1,2,Berserk,Berserk,ベルセルク,Manga,NaN,NaN,Publishing,True,1989-08-25,...,1,794592,137638,"Miura, Kentarou|Studio Gaga",Young Animal,Action|Adventure|Award Winning|Drama|Fantasy|H...,Gore|Military|Psychological,Seinen,"Guts, a former mercenary now known as the Blac...",https://myanimelist.net/images/manga/1/157897.jpg
2,3,20th Century Boys,20th Century Boys,20世紀少年,Manga,249.0,22.0,Finished,False,1999-09-27,...,24,310161,23009,"Urasawa, Naoki",Big Comic Spirits,Award Winning|Drama|Mystery|Sci-Fi,Historical|Psychological,Seinen,"As the 20th century approaches its end, people...",https://myanimelist.net/images/manga/5/260006.jpg
3,4,Yokohama Kaidashi Kikou,Yokohama Kaidashi Kikou,ヨコハマ買い出し紀行,Manga,142.0,14.0,Finished,False,1994-04-25,...,209,85859,5593,"Ashinano, Hitoshi",Afternoon,Award Winning|Sci-Fi|Slice of Life,Iyashikei,Seinen,In a post-apocalyptic world where an environme...,https://myanimelist.net/images/manga/1/171813.jpg
4,7,Hajime no Ippo,Hajime no Ippo: Fighting Spirit!,はじめの一歩,Manga,NaN,NaN,Publishing,True,1989-09-27,...,160,102198,7654,"Morikawa, George",Shounen Magazine (Weekly),Award Winning|Sports,Combat Sports,Shounen,Makunouchi Ippo is a 16-year-old high school s...,https://myanimelist.net/images/manga/2/250313.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82884,192758,Assistant Manager Kim Hates K-Pop Idols,Assistant Manager Kim Hates K-Pop Idols,김 대리는 아이돌이 싫어,Manhwa,NaN,NaN,Publishing,True,2025-09-24,...,81736,14,0,Peulmin|Toesayeonseubsaeng,Naver Webtoon,Drama,Idols (Male),NaN,Assistant Manager Kim Iwol has spent five year...,https://myanimelist.net/images/manga/3/344226.jpg
82885,192775,Elf-ppoi Hana-san no Tekitou na Apartment-gurashi,Elf-Like Hana's Casual Apartment Life,エルフっぽい花さんのてきと～なアパートぐらし,Manga,NaN,NaN,Publishing,True,2026-04-21,...,76104,31,0,"Arai, Cherry",Comic Newtype,Comedy|Supernatural,Adult Cast,NaN,"Hana, who lives in the cheap apartment next do...",https://myanimelist.net/images/manga/3/344262.jpg
82886,192778,Garden in the Closet,NaN,ガーデン・イン・ザ・クローゼット,Manga,NaN,NaN,Publishing,True,2026-04-03,...,82600,8,0,"Itono, Kei",Comic Nettai,Boys Love|Drama|Supernatural,School,NaN,Kouki is a high school student with a large bu...,https://myanimelist.net/images/manga/3/344281.jpg
82887,192789,Anta ga Warui,NaN,あんたが悪い,One-shot,1.0,NaN,Finished,False,2026-04-13,...,81542,15,0,"Hinoeda, Miyako",ComicWalker,Drama|Girls Love,School,NaN,"""I am only interested in people who seem into ...",https://myanimelist.net/images/manga/3/344300.jpg
82888,192804,Hirahirahira,Yohira's Travelogue,葩々々,Manga,NaN,NaN,Publishing,True,2026-04-21,...,81889,13,0,"Suzuki, Yuu",Comic Growl,Adventure|Fantasy|Slice of Life,NaN,NaN,"In a certain era, in a certain place. Yohira c...",https://myanimelist.net/images/manga/3/344323.jpg

In [2]:
df = df[df['published_from'].str.contains('2026', na=False)] # '2023|2024|2025|2026'
df.shape

(373, 24)

In [3]:
# df.dropna(subset=['title','score', 'authors', 'genres', 'themes', 'synopsis'])

In [4]:
df.loc[:, ['title','genres','synopsis']]

,title,genres,synopsis
72750,404 Chicks,Comedy,NaN
80732,One Cute Chick,Comedy,Chicktaro is too cute!\n\n\nI saw this story a...
81552,Dareka Ookami-san no Shitsukekata Shirimasen ka!?,Girls Love,"Himura Akane, a sophomore and member of the di..."
81574,Ano Shima no Uminesou,Mystery|Ecchi,Unemployed 19-year-old Kazuma has been summone...
81618,Winter Field,Boys Love|Fantasy|Erotica,"Rensley Mallosen, the illegitimate prince of C..."
...,...,...,...
82883,"Keiyaku shite yo, Sumi-senpai",Boys Love|Supernatural,"""The real me is far from being perfect.""\n\nKy..."
82885,Elf-ppoi Hana-san no Tekitou na Apartment-gurashi,Comedy|Supernatural,"Hana, who lives in the cheap apartment next do..."
82886,Garden in the Closet,Boys Love|Drama|Supernatural,Kouki is a high school student with a large bu...
82887,Anta ga Warui,Drama|Girls Love,"""I am only interested in people who seem into ..."
82888,Hirahirahira,Adventure|Fantasy|Slice of Life,"In a certain era, in a certain place. Yohira c..."

In [1]:
from database_module.vectordb import VectorDB

In [2]:
vdb = VectorDB("manga")

# vdb.create_db(df)

vdb.connect_db()

14-07-2026 10:36:39 - successfully load manga vector database

In [3]:
text = 'manga about a renowned Japanese neurosurgeon working in post-war Germany'
text = 'post-war Germany'
# text = synopsis:Four mischievous girls illegally occupy the former Traditional Tea Ceremony clubroom, in order to create the "Amusement Club." These scamps...who ignore repeated warnings—in direct rebellion with the righteous directives of the Student Council—decide to remain in the room until they finally get off their bums and do something! In this slightly sluggish manga, full of fits and starts, the four girls set off from their homes for a walk together with days full of a little this and that!♪

# (Source: JManga)
# text = """title:
# Yuru Yuri
#
# title_english:
# Yuru Yuri
#
# genres:
# Comedy
# Girls Love
# """
# text = _clean_text(text)
idx, dist = vdb.search_vector(text, k=5)
print(idx)
print(dist)

[11243, 426, 4404, 171218, 190586]
[0.83044267 0.83230627 0.8336984  0.8388977  0.83980846]

In [ ]:
def _clean_text(text):
    text = text.replace('|', ', ')
    text = re.sub(r"\(Source:.*?\)", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [16]:
import pandas as pd
import numpy as np

col_list = ['mal_id', 'title', 'title_english', 'type', 'chapters', 'volumes', 'status', 'published_from',
                        'published_to', 'score', 'authors', 'genres', 'themes', 'synopsis']
df = pd.read_csv('dataset/manga_dataset.csv')
df = df.loc[:30000, col_list]
df.dropna(subset=['title'], inplace=True)
df['mal_id'] = df['mal_id'].astype(int)

In [23]:
idx = 64919

print(df[df['mal_id'] == np.int64(idx)]['synopsis'].iloc[0])
df[df['mal_id'] == np.int64(idx)]

nan

,mal_id,title,title_english,type,chapters,volumes,status,published_from,published_to,score,authors,genres,themes,synopsis
25959,64919,Senjou no Mahoutsukai,The Wizard of battlefield,Manga,26.0,4.0,Finished,2013-12-27,2016-03-26,NaN,"Hiyama, Daisuke",Drama,Military|Super Power,NaN

In [11]:
import pandas as pd
import numpy as np

col_list = ['mal_id', 'title', 'title_english', 'type', 'chapters', 'volumes', 'status', 'published_from',
                        'published_to', 'score', 'authors', 'genres', 'themes', 'synopsis']
df = pd.read_csv('dataset/manga_dataset.csv')
df = df.loc[:10000, col_list]
df.dropna(subset=['title'], inplace=True)
df['mal_id'] = df['mal_id'].astype(int)

In [25]:
idx = 15006

print(df[df['mal_id'] == np.int64(idx)]['synopsis'].iloc[0])
df[df['mal_id'] == np.int64(idx)]

In a school where after school activities are mandatory among all students, Hajime and her friend Sayo come across a new club that they have never seen before. The club is called "The Cultural Activity Preservation Club." The two enter the room to find all kinds of analog jobs and activities, such as handcrafting mats and toothpicks. This is a unique cultural manga mixed with comedy so as not to bore you, this is Double-J!

(Source: MangaHelpers)

,mal_id,title,title_english,type,chapters,volumes,status,published_from,published_to,score,authors,genres,themes,synopsis
9831,15006,Double-J,NaN,Manga,106.0,6.0,Finished,2009-07-22,2011-10-26,NaN,"Nonaka, Eiji|Asakura, Maru",Comedy,School,In a school where after school activities are ...

In [ ]:
# df[df['mal_id'] == np.int64(14741)]['synopsis']
df[
    df['genres'].str.contains('Comedy', case=False, na=False) &
    df['genres'].str.contains('Girls Love', case=False, na=False)
].loc[:,['mal_id','title','genres','synopsis']]

In [ ]:
df.iloc[0]

In [ ]:
df.info()

In [ ]:
df.iloc[9663]['synopsis']

In [ ]:
# import pandas as pd
# col_list = ['mal_id', 'title', 'title_english', 'type', 'chapters', 'volumes', 'status', 'published_from',
#                         'published_to', 'score', 'authors', 'genres', 'themes', 'synopsis']
# df = pd.read_csv('dataset/manga_dataset.csv')
# df = df.loc[:1000, col_list]
# df.dropna(subset=['title'], inplace=True)
# df

In [ ]:
fillcol = {
  'title': '-',
  'title_english': '-',
  'type': '-',
  'chapters': 0,
  'volumes': 0,
  'status': '-',
  'published_from': '-',
  'published_to': '-',
  'score': 0,
  'authors': '-',
  'genres': '-',
  'themes': '-',
  'synopsis': '-'}
df.fillna(fillcol, inplace=True)

In [ ]:
df.isna().sum()

In [ ]:
df.info()

In [ ]:
import re

for data in df.iloc[:1].itertuples():
    print(re.sub(r'\s+', ' ', data.synopsis))

In [ ]:
def _make_document(dataframe):
    pattern = r'\s+'
    for data in dataframe.iloc[:3].itertuples():
        yield f'''
        title: {data.title}
        title_english: {data.title_english}
        type: {data.type}
        chapters: {data.chapters}
        volumes: {data.volumes}
        status: {data.status}
        published_from: {data.published_from}
        score: {data.score}
        authors: {data.authors}
        genres: {data.genres}
        themes: {data.themes}
        synopsis: {re.sub(pattern, " ", data.synopsis)}
        '''.strip()

for poi in _make_document(df):
    print(poi)
    print()

## Test RAG Controller

In [ ]:
4. When multiple manga are provided, clearly identify which manga the answer refers to.
                                        5. When recommendation are asked, explain recommendation based on provided context.

In [1]:
from rag_module.rag_controller import RAGAction, RAGModel

# ragc = RAGController(db_name='manga', timestamp='2026-07-10', inference_type=None, rebuild_rag=False)
# ragc = RAGController(db_name='manga', timestamp='2026-07-10', inference_type=None, rebuild_rag=True)
ragc = RAGAction(rag_name="manga", nlu_model_name="2026-07-10", inference_type=None)
ragc

15-07-2026 09:51:17 - manga.db connected successfully.
15-07-2026 09:51:17 - successfully load manga vector database
15-07-2026 09:51:17 - successfully connected to RAG database
15-07-2026 09:51:17 - [nlu_trainer] loading nlu model from 2026-07-10

In [2]:
ragc.sql_db._check_conn()

True

In [3]:
# stream test
text = 'tell me about Sangeki manga'
# text = 'do you have recommendation manga similar like Yuru Yuri'
for token in ragc.response_handler(text, verbose=1, stream=True):
    print(token, end='', flush=True)

intent metadata_lookup
ner [('MANGA_ENT', 'Sangeki')]
RH-1
sql side
possible_title ['Sangeki']
possible_authors []
query_filter1 'title:"Sangeki" OR title_english:"Sangeki"'ORDER BY score DESC
RH-1b
XXX SQL QUERY
            SELECT * FROM manga_fts
            WHERE manga_fts MATCH 'title:"Sangeki" OR title_english:"Sangeki"'ORDER BY score DESC
####### context ######

                <TARGET_MANGA>
                title:Sangeki
title_english:Haunted Peak
type:Manga
chapters:None
volumes:None
status:Publishing
published_from:2026-04-02
published_to:None
score:6.87
authors:Minenami, Ryou
genres:Drama|Mystery
themes:School
synopsis:High schooler Miko, who thought he'd be inheriting his grandfather's mountain, has lost his crush to his friend and is at the bottom of his school's hierarchy. His one solace was the mountain, but now a mysterious masked man is building a small cabin there... Tagline: Am I weak? A tale of love and hate spiraling around a mountain.
                </TARGET_MANGA>

                <USER_QUESTION>
                tell me about Sangeki manga
                </USER_QUESTION>

ValueError:

In [1]:
    def _metadata_query_search(metadata_target: dict, search_col: list[str], sort_rating: bool) -> str:
        query_filter = f"""\'"""
        first_key = True
        tmp = ""
        for k, v in metadata_target.items():
            if k not in search_col:
                continue
            v = v.replace('"', '\\"')
            if first_key:
                tmp = f"{k}:\"{v}\""
                first_key = False
            else:
                tmp = tmp + f" OR {k}:\"{v}\""

        query_filter = query_filter + tmp + "\'"
        if sort_rating:
            query_filter = query_filter + "ORDER BY score DESC"

        return query_filter

In [5]:
poi = {
        # 'title': 'Yuri',
       'genres': 'Comedy|Girls Love',
       'themes': 'Music',
        'synopsis':"Four mischievous girls illegally occupy the former Traditional Tea Ceremony clubroom, in order to create the "Amusement Club." These scamps...who ignore repeated warnings—in direct rebellion with the righteous directives of the Student Council—decide to remain in the room until they finally get off their bums and do something! In this slightly sluggish manga, full of fits and starts, the four girls set off from their homes for a walk together with days full of a little this and that!♪'
       }
search_col = ["genres", "themes","synopsis"]
mas = _metadata_query_search(poi, search_col,sort_rating=False)
print(mas)

SyntaxError: unterminated string literal (detected at line 5) (2184012896.py, line 5)

In [1]:
import sqlite3
conn = sqlite3.connect("data/manga.db")

In [5]:
col_list = ['mal_id', 'title', 'title_english', 'type', 'chapters', 'volumes', 'status', 'published_from', 'published_to', 'score', 'authors', 'genres', 'themes', 'synopsis']
context = '''Relevant context:\n'''

with sqlite3.connect("data/manga.db") as conn:
    cursor = conn.cursor()
    # cursor.execute(f"SELECT * FROM manga WHERE mal_id IN ({poi}) ORDER BY score DESC")
    # cursor.execute(f'SELECT * FROM manga WHERE title = "Ranma 1/2" ORDER BY score DESC')
    # cursor.execute(f'SELECT * FROM manga ORDER BY score DESC')

    # Query the manga_fts table instead of the standard manga table
    # cursor.execute("""
    # SELECT * FROM manga_fts
    # WHERE manga_fts MATCH 'genres:"Comedy|Girls Love" OR themes:"Music"'
    # """.strip())
    cursor.execute("""
    SELECT * FROM manga_fts
    WHERE manga_fts MATCH 'published_from:"2025" AND genres:"Girls Love"'
    """.strip())
    all_rows = cursor.fetchmany(5)  # Returns a list of tuples

    for row in all_rows:
        tmp = ' '.join(f'{col}: {val}\n ' for col, val in zip(col_list, row))
        context = context + tmp + '\n'
    print(context)

Relevant context:
mal_id: 179402
  title: Gal Oshi JK wa Gal ni Naritai
  title_english: None
  type: Manga
  chapters: 27.0
  volumes: 1.0
  status: Finished
  published_from: 2025-02-27
  published_to: None
  score: 6.49
  authors: Minami
  genres: Comedy|Girls Love
  themes: School
  synopsis: "Living as a gal is seriously the best!!"

Mimiru was an introvert in middle school, but when she entered high school, she made her long-awaited debut as a gal, thinking, "Maybe I can become a gal too!?" She made friends with three girls: Yuuhi, a cool beauty with a calm and pretty look; Fuuka, a cute gal with a soft and fluffy look; and Kurumi, a cheerful and energetic gal who is good at sports. Now she has joined the gal group she has always admired! While she lives the sparkling life she has always dreamed of, she also pushes herself too hard to keep up with her friends. And she also notices new feelings growing within her...

(Source: Kadokawa, translated)

mal_id: 179530
  title: Chou Shinuchuu yori Ai wo Komete
  title_english: Big Love from Ultra Deep Space
  type: Manga
  chapters: None
  volumes: None
  status: Publishing
  published_from: 2025-02-18
  published_to: None
  score: 7.03
  authors: Ashida, Kawozu
  genres: Girls Love
  themes: School
  synopsis: "I want to know more about you, the one who found me in this infinite universe."

Due to the trauma of her middle school days, Ten Teradate distanced herself from others at school. But one day, Lulu, a princess from a faraway planet, arrives and announces that she will become Ten's bride, and Ten's quiet and lonely school life is drastically changed...

(Source: Ichijinsha, translated)

mal_id: 180013
  title: Akuyaku Reijou no Oyome-sama
  title_english: None
  type: Manga
  chapters: None
  volumes: None
  status: Publishing
  published_from: 2025-02-14
  published_to: None
  score: 7.07
  authors: Kawano, Akiko
  genres: Fantasy|Girls Love
  themes: Anthropomorphic|Villainess
  synopsis: One day, Carina, a lady who has been groomed to be queen, suddenly has her engagement annulled by her fiancee, the prince. Now he is sending Carina into exile while standing beside her sister, Aurora, instead. Exiled to the far north, where beasts are said to dwell, Carina ventures out to investigate the identity of a disturbing sound and has a fateful encounter in the snow...? A predatory love fantasy between a lady sworn to revenge and a strange girl seeking love!

(Source: Bungeishunju, translated)

mal_id: 181331
  title: Ginsei no Proust
  title_english: Blue Proustian Moment
  type: Manga
  chapters: 25.0
  volumes: 3.0
  status: Finished
  published_from: 2025-04-26
  published_to: 2025-11-08
  score: 7.43
  authors: Emofuu
  genres: Drama|Girls Love
  themes: School
  synopsis: Kazuki, the daughter of a wealthy businessman, and a straight-A student at a prestigious school for girls, meets Moeka, a wild girl from a rowdy school. What becomes of Kazuki when witnessing a steamy moment between Moeka and her boyfriend leaves her all shaken up...?! Find out in this seaside tale of two polar opposites and their fated encounter.

(Source: MANGA Plus)

mal_id: 181331
  title: Ginsei no Proust
  title_english: Blue Proustian Moment
  type: Manga
  chapters: 25.0
  volumes: 3.0
  status: Finished
  published_from: 2025-04-26
  published_to: 2025-11-08
  score: 7.43
  authors: Emofuu
  genres: Drama|Girls Love
  themes: School
  synopsis: Kazuki, the daughter of a wealthy businessman, and a straight-A student at a prestigious school for girls, meets Moeka, a wild girl from a rowdy school. What becomes of Kazuki when witnessing a steamy moment between Moeka and her boyfriend leaves her all shaken up...?! Find out in this seaside tale of two polar opposites and their fated encounter.

(Source: MANGA Plus)

## NLU Training

In [ ]:
from nlu_module.nlu_component import NLUComponent

nluc = NLUComponent(timestamp=None, retrain_model=True)

In [ ]:
from nlu_module.nlu_component import NLUComponent

nluc = NLUComponent(timestamp='2026-06-24')

In [ ]:
text = 'what genre is Ore wa written by Nishimori published in 2024'
# text = 'manga with mystery romance avant garde drama released in 2022'
# text = 'please give me manga published in early 2021 with authors Hajime Moriyasu with score below 3.5'
# text = 'tell me more about Mikansei No.1: Jokyoku by Kobayashi Seno'
# text = 'do you have recommendation manga similar like Berserk'

# intent classification
print('intent:', nluc.predict_intent(text))

# NER detection
print('ner:', nluc.predict_ner(text))

In [ ]:
# # text = "what genre by Shuto Machino"
# import re
# m = re.search(
#     r'(.+?)\s+by\s+(.+)',
#     text,
#     flags=re.I
# )
#
# if m:
#     left = m.group(1)
#     right = m.group(2)
#
# left,  right

In [ ]:
import re

def _metadata_lookup_sql(message, nlu_model):
    message = re.sub(
        r'\b(?:by\s+author|with\s+author|have\s+author|written\s+by|created\s+by|illustrated\s+by)\b',
        'by',
        message,
        flags=re.I
    )
    m = re.search(
            r'(.+?)\s+by\s+(.+)',
            message,
            flags=re.I
        )
    possible_title = []
    possible_authors = []

    if m:
        print(m.group(1))
        possible_title = [f'{ent[1]}' for ent in nlu_model.predict_ner(m.group(1)) if ent[0] == 'MANGA_ENT']
        tmp_string = 'by ' + m.group(2)
        print(tmp_string)
        possible_authors = [f'{ent[1]}' for ent in nlu_model.predict_ner(tmp_string) if ent[0] == 'MANGA_ENT']

    else:
        possible_title = nlu_model.predict_ner(message)

    query = 'SELECT * FROM manga_fts WHERE manga_fts MATCH'
    # query = ''
    print(possible_title)
    # print(m)
    print(possible_authors)

    if possible_title:
        query = query + f'''\'(title:"{possible_title[0]}"'''
        query = query + f''' OR title_english:"{possible_title[0]}")'''

    if possible_authors:
        query = query + f''' AND authors:"{possible_authors[0]}"'''

    query = query + '\' ORDER BY score DESC'

    return query

query = _metadata_lookup_sql(text, nluc)
print(query)

In [ ]:
def _metadata_lookup_sql(nlu_model, message):
    query_filter = ''
    message = re.sub(
        r'\b(?:by\s+author|with\s+author|have\s+author|written\s+by|created\s+by|illustrated\s+by)\b',
        'by',
        message,
        flags=re.I
    )
    m = re.search(
        r'(.+?)\s+by\s+(.+)',
        message,
        flags=re.I
    )
    possible_title = []
    possible_authors = []

    if m:
        # print(m.group(1))
        possible_title = [f'{ent[1]}' for ent in nlu_model.predict_ner(m.group(1)) if ent[0] == 'MANGA_ENT']
        tmp_string = 'by ' + m.group(2)
        # print(tmp_string)
        possible_authors = [f'{ent[1]}' for ent in nlu_model.predict_ner(tmp_string) if ent[0] == 'MANGA_ENT']

    else:
        possible_title = nlu_model.predict_ner(message)

    # print(possible_title)
    # # print(m)
    # print(possible_authors)

    if possible_title:
        query_filter = query_filter + f'''\'(title:"{possible_title[0]}"'''
        query_filter = query_filter + f''' OR title_english:"{possible_title[0]}")'''

    if possible_authors:
        query_filter = query_filter + f''' AND authors:"{possible_authors[0]}"'''

    query_filter = query_filter + '\' ORDER BY score DESC'

    return query_filter

In [ ]:
query = 'SELECT * FROM manga_fts WHERE manga_fts MATCH'
poi = _metadata_lookup_sql(nluc, text)
query = query + poi
print(query)

In [ ]:
def _entity_extraction(message, nlu_model):
    allowed_entities = ['MANGA_ENT', 'GENRES', 'PERIOD','RATING']
    message = re.sub(
            r'\b(?:by\s+author|with\s+author|have\s+author|written\s+by|created\s+by|illustrated\s+by)\b',
            'by',
            message,
            flags=re.I
    )
    m = re.search(
        r'(.+?)\s+by\s+(.+)',
        message,
        flags=re.I
    )

    if m:
        # print(m.group(1))
        tmp1 = [ent for ent in nlu_model.predict_ner(m.group(1)) if ent[0] in allowed_entities]
        tmp_string = 'by ' + m.group(2)
        # print(tmp_string)
        tmp2 = [ent for ent in nlu_model.predict_ner(tmp_string) if ent[0] in allowed_entities]
        tmp2 = [
            ('AUTHORS', ent[1]) if ent[0] == 'MANGA_ENT' else ent
            for ent in tmp2
        ]
        entities = tmp1 + tmp2

    else:
        entities = [ent for ent in nlu_model.predict_ner(message) if ent[0] in allowed_entities]

    return entities

In [ ]:
text = 'give me recommendation  romance comedy slice of life released in 2022'
_entity_extraction(text, nluc)

In [ ]:
from database_module.sqldb import SQLDB

In [ ]:
# sqldb = SQLDB(db_name='manga',
#                source_path='dataset/manga_dataset.csv',
#                rebuild_db=True,
#                max_rows=10000
#                )

sqldb = SQLDB(db_name='manga',
               rebuild_db=False,
               )

In [ ]:
# col_list = ['mal_id', 'title', 'title_english', 'type', 'chapters', 'volumes', 'status', 'published_from',
#                     'published_to', 'score', 'authors', 'genres', 'themes', 'synopsis']
with sqldb.conn as conn:
    cursor = conn.cursor()
    # Query the manga_fts table instead of the standard manga table
    # cursor.execute('SELECT * FROM manga_fts WHERE title MATCH "Yuri" OR title_english MATCH "Yuri" ORDER BY score DESC')
    # cursor.execute('''
    # SELECT * FROM manga_fts WHERE manga_fts MATCH '(title:"Ore wa" OR title_english:"Ore wa")' ORDER BY score DESC
    # ''')

    # cursor.execute(query)
    # all_rows = cursor.fetchmany(100)
    # col_list1 = [desc[0] for desc in cursor.description]
    # for row in all_rows:
    #     tmp = ' '.join(f'{col}: {val}\n' for col, val in zip(col_list1, row))
    #
    #     print(tmp)

    cursor.execute('SELECT DISTINCT(genres) FROM manga')
    # extract all genres in db
    all_rows = cursor.fetchall()
    col_list_all = []
    for row in all_rows:
        if row[0]:
            col_list_all  = col_list_all + row[0].split('|')

    col_list_all = list(set(col_list_all))
    print(len(col_list_all))

In [ ]:
col_list_all

In [ ]:
conn.close()

In [ ]:
poi = {'FIELD': ['author', 'published'],
 'MANGA_ENT': ['Kabaneri Fortress no JoJo', 'Shuto Machino'],
 'PERIOD': ['2024']}

oip = 'WHERE'
' OR '.join(poi['MANGA_ENT'])

In [ ]:
from database_module.sqldb import SQLDB

sqldb = SQLDB('manga')

In [ ]:
sqldb.search_manga()